name: Build and Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # NOVO PASSO: Configurar o Node.js para poder rodar comandos NPM
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use a versão do Node.js compatível com seu projeto

    # NOVO PASSO: Instalar as dependências do projeto
    - name: Install dependencies
      run: npm install

    # NOVO PASSO: Construir o projeto (compilar .tsx para .js, etc.)
    - name: Build project
      run: npm run build

    # PASSO ATUALIZADO: Fazer o deploy da pasta de build (dist)
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        # ATENÇÃO AQUI: A fonte agora é a pasta 'dist'
        SOURCE_DIR: 'dist'
